version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: unless-stopped
    networks:
      - app-network

      
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '8080:8080'
    depends_on: 
      - mongo
    restart: unless-stopped
    networks:
      - app-network
    env_file: .env
    environment:
        - MONGO_USERNAME=$MONGO_USERNAME
        - MONGO_PASSWORD=$MONGO_PASSWORD  

networks:
  app-network:
    driver: bridge    

